### ISSUE TITLE
unable to setup user: cannot set uid to unmapped user in user namespace: unknown

### ISSUE THREAD

**Issue by m00nwtchr** [DigitallyRefined/docker-wireguard-tunnel#18]
I'm getting the `failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to setup user: cannot set uid to unmapped user in user namespace: unknown` error when using this docker image with User Namespace Remapping (https://docs.docker.com/engine/security/userns-remap/)

**Comment by DigitallyRefined** [comment]
I'm not sure if this is possible, as I believe that Wireguard and/or rinetd will need root/privileged access to be able to configure and start the tunnel. Though you might be able to this to work by following [How to run wireguard as non root user](https://www.reddit.com/r/WireGuard/comments/170mpae/how_to_run_wireguard_as_non_root_user/).
