### ISSUE TITLE
Treafik

### ISSUE THREAD

**Issue by ben-biber** [DigitallyRefined/docker-wireguard-tunnel#3]
Do you also have an working traefik example?

**Comment by eiqnepm** [comment]
https://github.com/DigitallyRefined/docker-wireguard-tunnel/blob/main/example-tls-traefik.md#example-using-docker-wireguard-tunnel-with-traefik

**Comment by eiqnepm** [comment]
I use it with Traefik. Are you able to show me your client and server Docker Compose files?

**Comment by ben-biber** [comment]
I got it working know.
But why does my proxied container still have Internet access after I kill the VPN connection?
I have trouble understanding how the connection works

**Comment by eiqnepm** [comment]
This container creates a link between two docker containers, allowing the server to access containers hosted by the peer. It does not effect the peers ability to connect to the internet.
